version: '3.8'

services:
  tempocerto-api:
    platform: linux/x86_64
    build: .
    container_name: tempocerto-api
    environment:
      - ENVIRONMENT=development
      - APP_VERSION=Local
      - LOG_LEVEL=DEBUG
      - APPLICATION_PORT=:8080
      - APPLICATION_ADDRESS=localhost
      - CORS_URL=http://localhost:8080
      - MYSQL_DBNAME=tempocerto_api
      - MYSQL_HOST=tempocerto-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - SECRET=000000
      - INTERVAL_GET_KEYS_TO_CREATE=10
    depends_on:
      - tempocerto-db
      - nats
    ports:
      - "8080:8080"
    networks:
      - tempocerto-bridge

networks:
  tempocerto-bridge:
    driver: bridge
