name: Update Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Read coverage value
        run: COVERAGE_VALUE=$(cat covarage.txt)
        id: coverage

      - name: Update README.md
        uses: actions-js/repo-utils@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: README.md
          operations: |
            - search: '{{COVERAGE_VALUE}}'
              replace: ${{ steps.coverage.outputs.COVERAGE_VALUE }}
